I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/settings/db.rpy", line 1, in script
    init python:
  File "game/settings/db.rpy", line 1, in script
    init python:
  File "game/settings/db.rpy", line 21, in <module>
    dan = Character(_("barmen"), kind=emi, image="", dynamic=True, color="#c8ffc8")
NameError: name 'emi' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/settings/db.rpy", line 1, in script
    init python:
  File "game/settings/db.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/settings/db.rpy", line 21, in <module>
    dan = Character(_("barmen"), kind=emi, image="", dynamic=True, color="#c8ffc8")
NameError: name 'emi' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
awakening 1.0
Mon Dec  5 20:37:41 2022
